// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/protos/services/loan_service.proto

package services

import (
	entities "github.com/Dorji/sberInterview/api/protos/entities"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_protos_services_loan_service_proto protoreflect.FileDescriptor

const file_api_protos_services_loan_service_proto_rawDesc = "" +
	"\n" +
	"&api/protos/services/loan_service.proto\x12\bservices\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1eapi/protos/entities/loan.proto2\xa2\x01\n" +
	"\vLoanService\x12K\n" +
	"\aExecute\x12\x15.entities.LoanRequest\x1a\x14.entities.LoanResult\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/execute\x12F\n" +
	"\x05Cache\x12\x16.google.protobuf.Empty\x1a\x15.entities.CacheResult\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/cacheB4Z2github.com/Dorji/sberInterview/api/protos/servicesb\x06proto3"

var file_api_protos_services_loan_service_proto_goTypes = []any{
	(*entities.LoanRequest)(nil), // 0: entities.LoanRequest
	(*emptypb.Empty)(nil),        // 1: google.protobuf.Empty
	(*entities.LoanResult)(nil),  // 2: entities.LoanResult
	(*entities.CacheResult)(nil), // 3: entities.CacheResult
}
var file_api_protos_services_loan_service_proto_depIdxs = []int32{
	0, // 0: services.LoanService.Execute:input_type -> entities.LoanRequest
	1, // 1: services.LoanService.Cache:input_type -> google.protobuf.Empty
	2, // 2: services.LoanService.Execute:output_type -> entities.LoanResult
	3, // 3: services.LoanService.Cache:output_type -> entities.CacheResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protos_services_loan_service_proto_init() }
func file_api_protos_services_loan_service_proto_init() {
	if File_api_protos_services_loan_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_services_loan_service_proto_rawDesc), len(file_api_protos_services_loan_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_services_loan_service_proto_goTypes,
		DependencyIndexes: file_api_protos_services_loan_service_proto_depIdxs,
	}.Build()
	File_api_protos_services_loan_service_proto = out.File
	file_api_protos_services_loan_service_proto_goTypes = nil
	file_api_protos_services_loan_service_proto_depIdxs = nil
}
