// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/protos/entities/loan.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObjectCost     int64                  `protobuf:"varint,1,opt,name=object_cost,json=objectCost,proto3" json:"object_cost,omitempty"`             // стоимость объекта
	InitialPayment int64                  `protobuf:"varint,2,opt,name=initial_payment,json=initialPayment,proto3" json:"initial_payment,omitempty"` // первоначальный взнос
	Months         int64                  `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"`                                       // срок
	Program        *LoanProgram           `protobuf:"bytes,4,opt,name=program,proto3" json:"program,omitempty"`                                      // блок программы кредита
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoanRequest) Reset() {
	*x = LoanRequest{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanRequest) ProtoMessage() {}

func (x *LoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanRequest.ProtoReflect.Descriptor instead.
func (*LoanRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{0}
}

func (x *LoanRequest) GetObjectCost() int64 {
	if x != nil {
		return x.ObjectCost
	}
	return 0
}

func (x *LoanRequest) GetInitialPayment() int64 {
	if x != nil {
		return x.InitialPayment
	}
	return 0
}

func (x *LoanRequest) GetMonths() int64 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *LoanRequest) GetProgram() *LoanProgram {
	if x != nil {
		return x.Program
	}
	return nil
}

// Блок программы кредита
type LoanProgram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salary        bool                   `protobuf:"varint,1,opt,name=salary,proto3" json:"salary,omitempty"`     // корпоративная программа
	Military      bool                   `protobuf:"varint,2,opt,name=military,proto3" json:"military,omitempty"` // военная ипотека
	Base          bool                   `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`         // базовая программа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanProgram) Reset() {
	*x = LoanProgram{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanProgram) ProtoMessage() {}

func (x *LoanProgram) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanProgram.ProtoReflect.Descriptor instead.
func (*LoanProgram) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{1}
}

func (x *LoanProgram) GetSalary() bool {
	if x != nil {
		return x.Salary
	}
	return false
}

func (x *LoanProgram) GetMilitary() bool {
	if x != nil {
		return x.Military
	}
	return false
}

func (x *LoanProgram) GetBase() bool {
	if x != nil {
		return x.Base
	}
	return false
}

// Блок агрегированных данных
type LoanAggregates struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rate            int64                  `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`                                               // ставка (% годовых)
	LoanSum         int64                  `protobuf:"varint,2,opt,name=loan_sum,json=loanSum,proto3" json:"loan_sum,omitempty"`                          // сумма кредита
	MonthlyPayment  int64                  `protobuf:"varint,3,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`     // платеж в месяц
	Overpayment     int64                  `protobuf:"varint,4,opt,name=overpayment,proto3" json:"overpayment,omitempty"`                                 // переплата
	LastPaymentDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_payment_date,json=lastPaymentDate,proto3" json:"last_payment_date,omitempty"` // дата последнего платежа
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoanAggregates) Reset() {
	*x = LoanAggregates{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanAggregates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanAggregates) ProtoMessage() {}

func (x *LoanAggregates) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanAggregates.ProtoReflect.Descriptor instead.
func (*LoanAggregates) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{2}
}

func (x *LoanAggregates) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LoanAggregates) GetLoanSum() int64 {
	if x != nil {
		return x.LoanSum
	}
	return 0
}

func (x *LoanAggregates) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *LoanAggregates) GetOverpayment() int64 {
	if x != nil {
		return x.Overpayment
	}
	return 0
}

func (x *LoanAggregates) GetLastPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPaymentDate
	}
	return nil
}

// Итоговый ответ
type LoanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *LoanParams            `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Program       *LoanProgram           `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"`
	Aggregates    *LoanAggregates        `protobuf:"bytes,3,opt,name=aggregates,proto3" json:"aggregates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanResult) Reset() {
	*x = LoanResult{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResult) ProtoMessage() {}

func (x *LoanResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResult.ProtoReflect.Descriptor instead.
func (*LoanResult) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{3}
}

func (x *LoanResult) GetParams() *LoanParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *LoanResult) GetProgram() *LoanProgram {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *LoanResult) GetAggregates() *LoanAggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

// Обертка для ответа (если нужно)
type LoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *LoanResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanResponse) Reset() {
	*x = LoanResponse{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResponse) ProtoMessage() {}

func (x *LoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResponse.ProtoReflect.Descriptor instead.
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{4}
}

func (x *LoanResponse) GetResult() *LoanResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CacheResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*LoanResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResult) Reset() {
	*x = CacheResult{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResult) ProtoMessage() {}

func (x *CacheResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResult.ProtoReflect.Descriptor instead.
func (*CacheResult) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{5}
}

func (x *CacheResult) GetResults() []*LoanResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Блок параметров кредита
type LoanParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObjectCost     int64                  `protobuf:"varint,1,opt,name=object_cost,json=objectCost,proto3" json:"object_cost,omitempty"`             // стоимость объекта (рубли)
	InitialPayment int64                  `protobuf:"varint,2,opt,name=initial_payment,json=initialPayment,proto3" json:"initial_payment,omitempty"` // первоначальный взнос
	Months         int64                  `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"`                                       // срок (месяцы)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoanParams) Reset() {
	*x = LoanParams{}
	mi := &file_api_protos_entities_loan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanParams) ProtoMessage() {}

func (x *LoanParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_entities_loan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanParams.ProtoReflect.Descriptor instead.
func (*LoanParams) Descriptor() ([]byte, []int) {
	return file_api_protos_entities_loan_proto_rawDescGZIP(), []int{6}
}

func (x *LoanParams) GetObjectCost() int64 {
	if x != nil {
		return x.ObjectCost
	}
	return 0
}

func (x *LoanParams) GetInitialPayment() int64 {
	if x != nil {
		return x.InitialPayment
	}
	return 0
}

func (x *LoanParams) GetMonths() int64 {
	if x != nil {
		return x.Months
	}
	return 0
}

var File_api_protos_entities_loan_proto protoreflect.FileDescriptor

const file_api_protos_entities_loan_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/protos/entities/loan.proto\x12\bentities\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\vLoanRequest\x12\x1f\n" +
	"\vobject_cost\x18\x01 \x01(\x03R\n" +
	"objectCost\x12'\n" +
	"\x0finitial_payment\x18\x02 \x01(\x03R\x0einitialPayment\x12\x16\n" +
	"\x06months\x18\x03 \x01(\x03R\x06months\x12/\n" +
	"\aprogram\x18\x04 \x01(\v2\x15.entities.LoanProgramR\aprogram\"U\n" +
	"\vLoanProgram\x12\x16\n" +
	"\x06salary\x18\x01 \x01(\bR\x06salary\x12\x1a\n" +
	"\bmilitary\x18\x02 \x01(\bR\bmilitary\x12\x12\n" +
	"\x04base\x18\x03 \x01(\bR\x04base\"\xd2\x01\n" +
	"\x0eLoanAggregates\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x03R\x04rate\x12\x19\n" +
	"\bloan_sum\x18\x02 \x01(\x03R\aloanSum\x12'\n" +
	"\x0fmonthly_payment\x18\x03 \x01(\x03R\x0emonthlyPayment\x12 \n" +
	"\voverpayment\x18\x04 \x01(\x03R\voverpayment\x12F\n" +
	"\x11last_payment_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastPaymentDate\"\xa5\x01\n" +
	"\n" +
	"LoanResult\x12,\n" +
	"\x06params\x18\x01 \x01(\v2\x14.entities.LoanParamsR\x06params\x12/\n" +
	"\aprogram\x18\x02 \x01(\v2\x15.entities.LoanProgramR\aprogram\x128\n" +
	"\n" +
	"aggregates\x18\x03 \x01(\v2\x18.entities.LoanAggregatesR\n" +
	"aggregates\"<\n" +
	"\fLoanResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.entities.LoanResultR\x06result\"=\n" +
	"\vCacheResult\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.entities.LoanResultR\aresults\"n\n" +
	"\n" +
	"LoanParams\x12\x1f\n" +
	"\vobject_cost\x18\x01 \x01(\x03R\n" +
	"objectCost\x12'\n" +
	"\x0finitial_payment\x18\x02 \x01(\x03R\x0einitialPayment\x12\x16\n" +
	"\x06months\x18\x03 \x01(\x03R\x06monthsB4Z2github.com/Dorji/sberInterview/api/protos/entitiesb\x06proto3"

var (
	file_api_protos_entities_loan_proto_rawDescOnce sync.Once
	file_api_protos_entities_loan_proto_rawDescData []byte
)

func file_api_protos_entities_loan_proto_rawDescGZIP() []byte {
	file_api_protos_entities_loan_proto_rawDescOnce.Do(func() {
		file_api_protos_entities_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_entities_loan_proto_rawDesc), len(file_api_protos_entities_loan_proto_rawDesc)))
	})
	return file_api_protos_entities_loan_proto_rawDescData
}

var file_api_protos_entities_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_protos_entities_loan_proto_goTypes = []any{
	(*LoanRequest)(nil),           // 0: entities.LoanRequest
	(*LoanProgram)(nil),           // 1: entities.LoanProgram
	(*LoanAggregates)(nil),        // 2: entities.LoanAggregates
	(*LoanResult)(nil),            // 3: entities.LoanResult
	(*LoanResponse)(nil),          // 4: entities.LoanResponse
	(*CacheResult)(nil),           // 5: entities.CacheResult
	(*LoanParams)(nil),            // 6: entities.LoanParams
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_protos_entities_loan_proto_depIdxs = []int32{
	1, // 0: entities.LoanRequest.program:type_name -> entities.LoanProgram
	7, // 1: entities.LoanAggregates.last_payment_date:type_name -> google.protobuf.Timestamp
	6, // 2: entities.LoanResult.params:type_name -> entities.LoanParams
	1, // 3: entities.LoanResult.program:type_name -> entities.LoanProgram
	2, // 4: entities.LoanResult.aggregates:type_name -> entities.LoanAggregates
	3, // 5: entities.LoanResponse.result:type_name -> entities.LoanResult
	3, // 6: entities.CacheResult.results:type_name -> entities.LoanResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_protos_entities_loan_proto_init() }
func file_api_protos_entities_loan_proto_init() {
	if File_api_protos_entities_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_entities_loan_proto_rawDesc), len(file_api_protos_entities_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protos_entities_loan_proto_goTypes,
		DependencyIndexes: file_api_protos_entities_loan_proto_depIdxs,
		MessageInfos:      file_api_protos_entities_loan_proto_msgTypes,
	}.Build()
	File_api_protos_entities_loan_proto = out.File
	file_api_protos_entities_loan_proto_goTypes = nil
	file_api_protos_entities_loan_proto_depIdxs = nil
}
